
#conectando banco de dados
spring:
  application:
    name: santander-dev-week-2024
  datasource:
    url: jdbc:h2:mem:sdw2024
    driver-class-name: org.h2.Driver
    username: sa
    password: 'oi'
  h2:
    console:
      enabled: true 
      settings:
        web-allow-others: true
